"""Markdown レポート生成層."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from bq_auditor.models.result import AuditResult, CostInsight, FullScanInsight, ZombieTableInsight

_BYTES_PER_GB: float = 1024**3


def _format_cost(usd: float) -> str:
    """USD コストをフォーマットする."""
    return f"${usd:.4f}"


def _truncate(text: str, max_len: int = 80) -> str:
    """テキストを指定文字数で切り詰める."""
    return text[:max_len] + "..." if len(text) > max_len else text


def generate_markdown_report(result: AuditResult, filepath: str = "report.md") -> None:
    """AuditResult を Markdown 形式のレポートファイルとして出力する.

    CI/CD の Artifact として保存したり、社内 Wiki に貼り付けることを想定しています。
    末尾にビジネス導線を含みます。

    Args:
        result: Analyzer から受け取った監査結果
        filepath: 出力先ファイルパス (デフォルト: "report.md")
    """
    lines: list[str] = []
    generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # ヘッダー
    lines += [
        "# 🚀 BQ-Auditor 監査レポート",
        "",
        f"> **生成日時:** {generated_at}  ",
        f"> **プロジェクト:** `{result.project_id}`  ",
        f"> **分析期間:** 過去 {result.analyzed_days} 日間  ",
        f"> **分析ジョブ数:** {result.total_jobs_analyzed:,} 件  ",
        f"> **分析テーブル数:** {result.total_tables_analyzed:,} 件  ",
        "",
        "---",
        "",
    ]

    # サマリー
    lines += [
        "## 📊 サマリー",
        "",
        "| 指標 | 件数 |",
        "|------|------|",
        f"| 💸 高コストクエリ | {len(result.top_expensive_queries)} 件 |",
        f"| 🚨 フルスキャン検知 | {len(result.full_scans)} 件 |",
        f"| 🧟 ゾンビテーブル | {len(result.zombie_tables)} 件 |",
        "",
        "---",
        "",
    ]

    # 高コストクエリ
    lines += [
        "## 💸 高コストクエリ Top",
        "",
    ]
    if result.top_expensive_queries:
        lines += [
            "| 順位 | ユーザー | スキャン (TB) | 推定コスト (USD) | クエリ |",
            "|------|---------|-------------|---------------|-------|",
        ]
        for i, insight in enumerate(result.top_expensive_queries, 1):
            cost_insight: CostInsight = insight
            query_snippet = _truncate(insight.job.query.replace("\n", " "), 60)
            lines.append(
                f"| {i} "
                f"| `{cost_insight.job.user_email}` "
                f"| {cost_insight.scanned_tb:.4f} "
                f"| {_format_cost(cost_insight.estimated_cost_usd)} "
                f"| `{query_snippet}` |"
            )
    else:
        lines.append("✅ 高コストクエリは検出されませんでした。")
    lines += ["", "---", ""]

    # フルスキャン
    lines += [
        "## 🚨 フルスキャン検知",
        "",
        "> **インサイト:** パーティションテーブルの設計、またはクエリのフィルタリング見直しが必要です。",
        "",
    ]
    if result.full_scans:
        lines += [
            "| ユーザー | スキャン (GB) | クエリ |",
            "|---------|------------|-------|",
        ]
        for full_scan_insight in result.full_scans:
            full_scan: FullScanInsight = full_scan_insight
            query_snippet = _truncate(full_scan.job.query.replace("\n", " "), 60)
            lines.append(f"| `{full_scan.job.user_email}` | {full_scan.scanned_gb:.2f} | `{query_snippet}` |")
    else:
        lines.append("✅ フルスキャンは検出されませんでした。")
    lines += ["", "---", ""]

    # ゾンビテーブル
    lines += [
        "## 🧟 ゾンビテーブル",
        "",
        "> **インサイト:** これらのテーブルを削除、または Cloud Storage 等へ退避させることで"
        "ストレージコストを削減できます。",
        "",
    ]
    if result.zombie_tables:
        lines += [
            "| テーブル | 未使用日数 | サイズ (GB) |",
            "|---------|----------|-----------|",
        ]
        for zombie_insight in result.zombie_tables:
            zombie: ZombieTableInsight = zombie_insight
            lines.append(f"| `{zombie.table.full_table_id}` | {zombie.days_unused} 日以上 | {zombie.size_gb:.2f} |")
    else:
        lines.append("✅ ゾンビテーブルは検出されませんでした。")
    lines += ["", "---", ""]

    # ビジネス導線（仕様書指定）
    lines += [
        "## 💼 エンタープライズサポートのご案内",
        "",
        "BQ-Auditor は、データ基盤の「課題を発見する」ための強力な健康診断ツールです。",
        "発見された重症な課題（複雑なデータモデルの再設計や、大規模なクエリのリファクタリング）について、",
        "専門的なコンサルティング・エンジニアリング支援が必要な場合はお気軽にご相談ください。",
        "",
        "**対応可能な支援内容:**",
        "",
        "- 📐 パーティション設計・クラスタリング最適化",
        "- 🔄 dbt を用いたモダンデータモデリングへの移行",
        "- 🔒 データガバナンス体制の構築",
        "- 📊 CI/CD への BQ-Auditor 組み込み支援",
        "",
        "**👉 ご相談・お問い合わせ:** [あなたのポートフォリオサイトのURL] または [メールアドレス] まで。  ",
        "**初回ヒアリング・コスト削減ポテンシャルの簡易アセスメントは無料**で承ります。",
        "",
        "---",
        "",
        "_Generated by [BQ-Auditor](https://github.com/your-org/bq-auditor) — Zero Data Access, Maximum Insight._",
    ]

    output_path = Path(filepath)
    output_path.write_text("\n".join(lines), encoding="utf-8")
